version: '3'

networks:
  springapi:
    driver: bridge

services:
  mysqldb:
    image: mysql:8.0
    networks:
      - springapi
    environment:
      - MYSQL_ROOT_PASSWORD=teste123
      - MYSQL_DATABASE=account
      - MYSQL_TCP_PORT=3306

  springapi:
    build:
      context: .
    restart: on-failure
    networks:
      - springapi
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb:3306/account
      - MYSQL_USER=root
      - MYSQL_PASS=teste123
    ports:
      - 8080:8080
    depends_on:
      - mysqldb