pipeline {
    environment {
        registry = "localhost:8081/repository/bank-docker"
        image = "bankboot"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
    }

    agent any
    stages {
        stage('Building our image') {
            steps{
                script {
                    dockerImage = docker.build registry image + ":$BUILD_NUMBER"
                }
            }
        }

        stage('Deploy our image') {
            steps{
                script {
                    docker.withRegistry( "http://" + registry, registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Cleaning up') {
            steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}