pipeline {
    environment {
        registry = "localhost:8081/repository/bank-docker"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
    }

    agent any
    stages {
        stage('Building our image') {
            steps{
                dir("app"){
                    script {
                        dockerImage = docker.build registry + "/bankboot:$BUILD_NUMBER"
                    }
                }
            }
        }

        stage('Deploy our image') {
            steps{
                script {
                    docker.withRegistry( "http://" + registry + "/bankboot:$BUILD_NUMBER", registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Cleaning up') {
            steps{
                sh "docker rmi $registry/bankboot:$BUILD_NUMBER"
            }
        }
    }
}