version: '3'

networks:
  devops:
    driver: bridge

services:
  jenkins:
    build: .
    container_name: jenkins-server
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - devops

  sonarqube:
    image: sonarqube:9.4.0-community
    container_name: sonarqube-server
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - devops

  nexus:
    image: sonatype/nexus3:3.38.1
    container_name: nexus-server
    ports:
      - 8081:8081
      - 9001:9001
    networks:
      - devops
