pipeline {
    environment {
        registry = "localhost:9001"
        registryCredential = 'nexus'
        dockerImage = ''
        dockerImageLatest = ''
    }

    agent any
    stages {
        stage('Building our image') {
            steps{
                dir("app"){
                    script {
                        dockerImage = docker.build registry + "/bankboot:$BUILD_NUMBER"
                    }
                }
            }
            steps{
                dir("app"){
                    script {
                        dockerImageLatest = docker.build registry + "/bankboot:latest"
                    }
                }
            }
        }

        stage('Deploy our image') {
            steps{
                script {
                    docker.withRegistry("http://" + registry, registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
            steps{
                script {
                    docker.withRegistry("http://" + registry, registryCredential ) {
                        dockerImageLatest.push()
                    }
                }
            }
        }

        stage('Cleaning up') {
            steps{
                sh "docker rmi $registry/bankboot:$BUILD_NUMBER"
            }
            steps{
                sh "docker rmi $registry/bankboot:latest"
            }
        }
    }
}